# Generated by Django 5.0.8 on 2024-10-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=100)),
                ('dropoff', models.CharField(max_length=100)),
                ('pickupdate', models.CharField(max_length=100)),
                ('dropoffdate', models.CharField(max_length=100)),
                ('pickuptime', models.CharField(max_length=100)),
            ],
        ),
    ]
