# Generated by Django 5.0.8 on 2024-10-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_address', models.CharField(max_length=100)),
                ('office_email', models.CharField(max_length=100)),
                ('office_mobile', models.CharField(max_length=15)),
                ('office_facebook', models.CharField(max_length=30)),
                ('office_instagram', models.CharField(max_length=30)),
                ('office_linkedin', models.CharField(max_length=30)),
            ],
        ),
    ]
