# Generated by Django 5.0.8 on 2024-10-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('himg', models.ImageField(upload_to='static/')),
                ('hheading', models.CharField(max_length=100)),
                ('hparag', models.CharField(max_length=100)),
                ('aimg', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
