# Generated by Django 5.0.8 on 2024-10-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cprice', models.CharField(max_length=20)),
                ('cimg', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
