# Generated by Django 5.0.8 on 2024-10-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_carinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abheading', models.CharField(max_length=100)),
                ('abtext', models.CharField(max_length=1000)),
            ],
        ),
    ]
