# Generated by Django 5.0.8 on 2024-10-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_aboutinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timg', models.ImageField(upload_to='static/')),
                ('tinfo', models.CharField(max_length=300)),
                ('tname', models.CharField(max_length=30)),
                ('tpos', models.CharField(max_length=40)),
            ],
        ),
    ]
