# Generated by Django 5.0.8 on 2024-10-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_testinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blimg', models.ImageField(upload_to='static/')),
                ('bldate', models.CharField(max_length=20)),
                ('bltext', models.CharField(max_length=300)),
                ('blhead', models.CharField(max_length=100)),
            ],
        ),
    ]
